name: personal_finance_app
description: An App to Manage your household finances
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  firebase_core: ^3.10.0
  firebase_auth: ^5.4.0
  cloud_firestore: ^5.6.1
  equatable: ^2.0.7
  flutter_bloc: ^8.1.6
  bloc_test: ^9.1.7
  go_router: ^7.1.1
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  built_value: ^8.9.3
  connectivity_plus: ^4.0.2
  network_image_mock: ^2.1.1
  uuid: ^3.0.7
  intl: ^0.18.1
  fpdart: ^0.6.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  mockito: ^5.4.0
  build_runner: ^2.4.4
  built_value_generator: ^8.5.0
  hive_generator: ^2.0.0
  
flutter:
  uses-material-design: true
