// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCBMJKOFXUAGygEDNVplqyvlpQ-MblF1kM',
    appId: '1:772228312833:web:78c16b6acdb845ce8e3500',
    messagingSenderId: '772228312833',
    projectId: 'personal-finance-app-236f7',
    authDomain: 'personal-finance-app-236f7.firebaseapp.com',
    storageBucket: 'personal-finance-app-236f7.firebasestorage.app',
    measurementId: 'G-436HD27MRQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAJNRwO101H0UqvQhNUBrJq-G9OfEKZbn4',
    appId: '1:772228312833:android:de1b8810d93dfa628e3500',
    messagingSenderId: '772228312833',
    projectId: 'personal-finance-app-236f7',
    storageBucket: 'personal-finance-app-236f7.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCb-OAAHJctTn0sWn8N_4q0X9rd3mVy9S8',
    appId: '1:772228312833:ios:c5b70a912f6c5d5f8e3500',
    messagingSenderId: '772228312833',
    projectId: 'personal-finance-app-236f7',
    storageBucket: 'personal-finance-app-236f7.firebasestorage.app',
    iosBundleId: 'com.example.flutterTddAndCleanArchitecture',
  );
}
